### PR TITLE
Support (.tar).bz2 archives

### LINKED ISSUE #80: Feature Request: Support bzip2 / bz2 archives
Support for bzip2 / bz2 / tar.bzip2 / tar.bz2 archives.

Example: github.com/xo/usql

Split from #79.

### PR DESCRIPTION
**Pull request by sirlatrom**
E.g. https://github.com/xo/usql/releases/tag/v0.8.2.

Fixes #80.

### CODE REVIEW

**Comment by korpa** [comment]
I tried to install restic (https://github.com/restic/restic/releases/tag/v0.12.1) which is a bzip2ed binary. But I get following error:

```shell
$ bin install github.com/restic/restic 
   • Getting latest release for restic/restic
   • Starting download of https://github.com/restic/restic/releases/download/v0.12.1/restic_0.12.1_linux_amd64.bz2
5.92 MiB / 5.92 MiB [------------------------------------------------------------------------------------------------------] 100.00% 102.02 MiB p/s 0s
   ⨯ command failed            error=Error installing binary: open /home/user/bin: file exists
```

So I wonder if bzip2ed binaries are not supported at the moment?

**Comment by marcosnils** [comment]
hey @korpa seems like the error that you're getting is because restic already exists. Have you tried doing `bin update restic`?

**Comment by korpa** [comment]
Hej @marcosnils,

No, it doesn't exist. Furthermore then the error would not be 
`⨯ command failed            error=Error installing binary: open /home/user/bin: file exists`
but
`⨯ command failed            error=Error installing binary: open /home/user/bin/restic: file exists`

But I double checked it again:

```shell
$ cd ~/bin
$ ./restic
zsh: command not found: ./restic
$ ls ./restic
"./restic": No such file or directory (os error 2)
$  bin install github.com/restic/restic
   • Getting latest release for restic/restic
   • Starting download of https://github.com/restic/restic/releases/download/v0.12.1/restic_0.12.1_linux_amd64.bz2
5.92 MiB / 5.92 MiB [-------------------------------------------------------------------------------------------------------] 100.00% 23.83 MiB p/s 0s
   ⨯ command failed            error=Error installing binary: open /home/pauli/bin: file exists
```

But if you say it bzip2ed binaries like restic should work, the issue may be my bin "directory". Because it is not a directory but a symlink to `~/Workspace/dotfiles/bin`.

**Comment by marcosnils** [comment]
> But if you say it bzip2ed binaries like restic should work

I thought it was supported, but seems like it's not indeed. Also, we need to fix the error message as well. 

Would you mind opening an issue to track it? If you want to give it a shot with a PR, we'd appreciate the contribution!

**Comment by marcosnils** [comment]
Just found what's happening. `bin` has support for `.tar.bz2` files, but not just `.bz2` files. 

Definitely an "feature" we need to address. Mind adding that please?

**Comment by korpa** [comment]
I did a test in the meanwhile as well regarding the symlinked bin dir.

```shell
$ mv bin bin_bak
$ mkdir bin
$ install github.com/restic/restic
   • Getting latest release for restic/restic
   • Starting download of https://github.com/restic/restic/releases/download/v0.12.1/restic_0.12.1_linux_amd64.bz2
5.92 MiB / 5.92 MiB [--------------------------------------------------------------------------------------------------------] 100.00% 8.38 MiB p/s 1s
   ⨯ command failed            error=Error installing binary: open /home/user/bin: file exists
```

Same issue. So it is not the symlink.

**Pull request merged**
