### PR TITLE
Fix XZed binaries similar to bzip2ed binaries

### PR DESCRIPTION
**Pull request by korpa**
Fix XZed binaries similar to bzip2ed binaries.

Similar to #117

### CODE REVIEW

**Comment by marcosnils** [comment]
hey @korpa , how did you test this? Not sure if this is required for `xz` since XZ is different that bz2 in the sense that `xz` does suppor file listing.

**Comment by korpa** [comment]
I haven't tested it in real, but my assumption was that it works similar to bzip2 because I did following in a shell:

```shell
$ touch test-xz.txt
$ xz test-xz.txt
$ ls test-xz.txt.xz
test-xz.txt.xz
$ unxz test-xz.txt.xz
$ ls test-xz.txt
test-xz.txt
```

**Comment by marcosnils** [comment]
> I haven't tested it in real, but my assumption was that it works similar to bzip2 because I did following in a shell:

Hmmm.. intersting.. I see that `xz(1)` has an option `-l` to list information about files that `bzip2` doesn't have. So I thought it could be holding metadata about files but that doesn't seem to be the case.

**Comment by korpa** [comment]
Now I was unsure if xz may be used like bzip2 on the one hand and like zip on the other hand. But checking https://www.kernel.org I say, that the use tar.xz for the kernel (https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.6.tar.xz).

Furthermore I check the help of xz:

```
-l, --list          list information about .xz files
```

```shell
$ xz -l test-xz.txt.xz
Strms  Blocks   Compressed Uncompressed  Ratio  Check   Filename
    1       0         32 B          0 B    ---  CRC64   test-xz.txt.xz
```

It really only lists compression infos. So I think my fix is right. But never the less, it would be good to have real world example to test.

Thanks that you already merged it.

**Pull request merged**
