### PR TITLE
shorter bin install commands

### LINKED ISSUE #171: shorter bin install command
First of all, thanks for making this awesome tool.

I also noticed many many tools you [just download it and extract it then it works] and there is no need for multiple versions, the latest version is ok enough. so many plugins for asdf or rtx are [redundant](https://github.com/jdxcode/rtx/discussions/686) I think. 
and brew is far from perfect, it's ok on macOS, but not on linux. and original author mxcl is working on tea.xyz now.  With this nice bin tool, it's no need to wget then extract. and no need to install rtx plugins or asdf plugins.

But we can make it better,  like `gh repo clone marcosnils/bin`,  why we need to type github.com. for the releases on GitHub.com can cover 80% of the cases. and been even lazier or there are times when we don't memorize the username. so if there is a default shorthands like [this](https://github.com/jdxcode/rtx/blob/main/src/default_shorthands.rs) could help a lot.

I've draft a simple [pr](#170), with this pr. when I want to install ripgrep. I can just type `bin i rg`

### PR DESCRIPTION
**Pull request by dfang**
close #171

### CODE REVIEW

**Comment by marcosnils** [comment]
hey! thx for the contribution! Your PR gave me an idea. How about if we add a new command like `bin alias` to add or remove those aliases that can be stored in bin's config?

We could include the shorthands that you're proposing here as a default during config init or maybe through `bin alias add --default` to populate them. 

Thoughts?

**Comment by dfang** [comment]
`bin alias` is good, but it should not be the top priority thing.  as people can contribute to this file.

I think for the moment smart choose is more important. I mean for this case, 3 should be chosen. I noticed there are issues out on the list.

```
λ bin i dandavison/delta
   • Getting latest release for dandavison/delta
   • Starting download of https://api.github.com/repos/dandavison/delta/releases/assets/111116981
2.53 MiB / 2.53 MiB [---------------------------------------------------------------------------------] 100.00% 122.77 KiB p/s 22s

Multiple matches found, please select one:

 [1] delta-0.16.5-x86_64-apple-darwin/LICENSE
 [2] delta-0.16.5-x86_64-apple-darwin/README.md
 [3] delta-0.16.5-x86_64-apple-darwin/delta
 Select an option:
```

**Comment by marcosnils** [comment]
> `bin alias` is good, but it should not be the top priority thing. as people can contribute to this file.

I agree... but I think moving that file shorthands to the `bin` config even without the `bin alias` command would be something very useful as users will be able to add / remove  shorthands by manually editing the config file. WDYT?



> I think for the moment smart choose is more important. I mean for this case, 3 should be chosen. I noticed there are issues out on the list.

yes, agree. I have some ideas on how to improve this, just need to find the time to try them out.

**Comment by dfang** [comment]
> > `bin alias` is good, but it should not be the top priority thing. as people can contribute to this file.
> 
> I agree... but I think moving that file shorthands to the `bin` config even without the `bin alias` command would be something very useful as users will be able to add / remove shorthands by manually editing the config file. WDYT?

it helps ...

**Comment by marcosnils** [comment]
> it helps ...

would you be interested in making this refactor? I can tackle whenever I find some bandwidth though.

**Comment by dfang** [comment]
I think from the perspective of keeping it simple it's not necessary, with this PR, the most widely used tools should be covered, and the else could be installed by `bin i <USER>/<REPO>`. this could make config file simple.

**Comment by marcosnils** [comment]
:+1:. I'll refactor when I find the time. In the meantime I'll hold this PR since I don't want to hardcode custom shorthands in the code that will require a new release every time someone wants to add a new one.

**Comment by dfang** [comment]
Can you enable the discussions feature for this repo?

**Comment by marcosnils** [comment]
Sure, done

**Comment by dfang** [comment]
@marcosnils thanks, https://github.com/marcosnils/bin/discussions/172

**Comment by marcosnils** [comment]
closing since this didn't get too much traction and it has been stale for a while

**Pull request closed without merging**
