### PR TITLE
feat: improves `bin ls` output

### PR DESCRIPTION
**Pull request by yozachar**
- Using tabs, caused in-consistent spacing across softwares.
- This commit resolves in-consistent tab spacing with simple spaces.

### CODE REVIEW

**Review by marcosnils — APPROVED** [review]

**Comment by yozachar** [comment]
| before | after |
| --- | --- |
| before | after |

**Comment by yozachar** [comment]
@marcosnils, can these changes be merged?

**Comment by marcosnils** [comment]
done! merged and released in v0.17.5

**Comment by yozachar** [comment]
> Thx for the contribution

Delighted to contribute!

**Pull request merged**
