### PR TITLE
Started with a list of interesting tools which can be managed by 'bin'

### PR DESCRIPTION
**Pull request by korpa**
@marcosnils What do think about such a list. I like those lists to find new interesting tools.

### CODE REVIEW

**Comment by marcosnils** [comment]
hey @korpa I personally don't like bloating the README file with this list since it could potentially become very extensive. 

I do see the value on this though. Maybe creating a wiki page could be better and then link it from the README file.

**Comment by korpa** [comment]
That's fine for me as well. Would you mind to create a wiki page because when I click on "Wiki", I directly get redirected back to "Code".

**Comment by marcosnils** [comment]
Sure. Will do!

sent from mobile

Em dom, 5 de dez de 2021 09:50, korpa ***@***.***> escreveu:

**Comment by marcosnils** [comment]
:heavy_check_mark:  just invited you as a collaborator so you can add info to the wiki

**Comment by korpa** [comment]
Thank you very much

**Comment by marcosnils** [comment]
hey @korpa please don't auto merge PR's..wait for it to be approved by someone else before merging

**Comment by korpa** [comment]
Oh sorry. As it was open a few days with no comments and it was just a change in the readme, I merged it myself.

**Pull request merged**
