### PR TITLE
feat: Bump Go version to 1.19

### PR DESCRIPTION
**Pull request by mbevc1**
* Bump Go to 1.19, amend the pipeline and update dependencies
* Run `gofmt` on the codebase
* Add initial Makefile

### CODE REVIEW

**Review by marcosnils — APPROVED** [review]

**Comment by mbevc1** [comment]
Would it make sense to cut a new release using newer Go?

**Comment by marcosnils** [comment]
sure. I'll do that in a sec. Thx for the contributions btw!

**Comment by marcosnils** [comment]
done! v0.15.2 released!

**Comment by mbevc1** [comment]
Awesome, cheers!

**Pull request merged**
